import type { Candidate, Job } from '@/types/models';

// Mock candidates data
export const mockCandidates: Candidate[] = [
  {
    id: '1',
    firstName: 'Иван',
    lastName: 'Петров',
    middleName: 'Сергеевич',
    phone: '+7 999 111-22-33',
    birthDate: '1996-04-12',
    position: 'Менеджер по продажам',
    resumeLink: 'https://example.com/resume1.pdf',
    status: 'Новый',
    jobId: 'JOB001',
    lastUpdated: '2024-01-15',
    contactPoints: [
      {
        id: 'cp-1',
        type: 'Перезвон',
        dateTime: '2024-01-19T11:00:00',
        title: 'Перезвонить кандидату',
        description: 'Уточнить удобное время собеседования',
        done: false,
        createdAt: '2024-01-15T09:10:00',
      },
    ],
  },
  {
    id: '2',
    firstName: 'Мария',
    lastName: 'Сидорова',
    middleName: 'Игоревна',
    phone: '+7 999 222-33-44',
    birthDate: '1992-10-03',
    position: 'Специалист по негабариту',
    resumeLink: 'https://example.com/resume2.pdf',
    status: 'Перезвон',
    jobId: 'JOB002',
    lastUpdated: '2024-01-16',
    contactPoints: [
      {
        id: 'cp-2',
        type: 'Собеседование 1 этап',
        dateTime: '2024-01-20T14:00:00',
        title: 'Собеседование 1 этап',
        description: 'Видео/телефон',
        done: false,
        createdAt: '2024-01-16T12:00:00',
      },
    ],
  },
  {
    id: '3',
    firstName: 'Алексей',
    lastName: 'Козлов',
    middleName: 'Андреевич',
    phone: '+7 999 333-44-55',
    birthDate: '1999-02-21',
    position: 'Менеджер по продажам',
    resumeLink: 'https://example.com/resume3.pdf',
    status: 'Назначено собеседование 1 этап',
    jobId: 'JOB001',
    lastUpdated: '2024-01-17',
  },
  {
    id: '4',
    firstName: 'Елена',
    lastName: 'Новикова',
    middleName: 'Викторовна',
    phone: '+7 999 444-55-66',
    birthDate: '1994-07-08',
    position: 'Специалист по негабариту',
    resumeLink: 'https://example.com/resume4.pdf',
    status: 'Проведено собеседование 1 этап',
    jobId: 'JOB002',
    lastUpdated: '2024-01-18',
  },
  {
    id: '5',
    firstName: 'Дмитрий',
    lastName: 'Волков',
    middleName: 'Павлович',
    phone: '+7 999 555-66-77',
    birthDate: '1997-11-19',
    position: 'Менеджер по продажам',
    resumeLink: 'https://example.com/resume5.pdf',
    status: 'Отказ кандидата',
    jobId: 'JOB001',
    lastUpdated: '2024-01-19',
    contactPoints: [],
  },
  {
    id: '6',
    firstName: 'Анна',
    lastName: 'Смирнова',
    middleName: 'Олеговна',
    phone: '+7 999 666-77-88',
    birthDate: '1995-01-30',
    position: 'Специалист по негабариту',
    resumeLink: 'https://example.com/resume6.pdf',
    status: 'Недозвон',
    jobId: 'JOB002',
    lastUpdated: '2024-01-20',
  },
  {
    id: '7',
    firstName: 'Сергей',
    lastName: 'Морозов',
    middleName: 'Владимирович',
    phone: '+7 999 777-88-99',
    birthDate: '1993-05-14',
    position: 'Менеджер по продажам',
    resumeLink: 'https://example.com/resume7.pdf',
    status: 'Назначено собеседование 2 этап',
    jobId: 'JOB001',
    lastUpdated: '2024-01-21',
  },
  {
    id: '8',
    firstName: 'Ольга',
    lastName: 'Кузнецова',
    middleName: 'Михайловна',
    phone: '+7 999 888-99-00',
    birthDate: '1998-09-02',
    position: 'Специалист по негабариту',
    resumeLink: 'https://example.com/resume8.pdf',
    status: 'Кадровый резерв',
    jobId: 'JOB002',
    lastUpdated: '2024-01-22',
  },
];

// Mock jobs data
export const mockJobs: Job[] = [
  {
    jobId: 'JOB001',
    jobTitle: 'Менеджер по продажам',
    department: 'Продажи',
    status: 'Open',
  },
  {
    jobId: 'JOB002',
    jobTitle: 'Специалист по негабариту',
    department: 'Логистика',
    status: 'Open',
  },
];
