import type { Candidate, Job } from '@/types/models';

// Mock candidates data
export const mockCandidates: Candidate[] = [
  {
    id: '1',
    firstName: 'Иван',
    lastName: 'Петров',
    age: 28,
    experienceYears: 5,
    position: 'Менеджер по продажам',
    resumeLink: 'https://example.com/resume1.pdf',
    status: 'New',
    jobId: 'JOB001',
    lastUpdated: '2024-01-15',
  },
  {
    id: '2',
    firstName: 'Мария',
    lastName: 'Сидорова',
    age: 32,
    experienceYears: 8,
    position: 'Специалист по негабариту',
    resumeLink: 'https://example.com/resume2.pdf',
    status: 'In Progress',
    jobId: 'JOB002',
    lastUpdated: '2024-01-16',
  },
  {
    id: '3',
    firstName: 'Алексей',
    lastName: 'Козлов',
    age: 25,
    experienceYears: 3,
    position: 'Менеджер по продажам',
    resumeLink: 'https://example.com/resume3.pdf',
    status: 'Interview',
    jobId: 'JOB001',
    lastUpdated: '2024-01-17',
  },
  {
    id: '4',
    firstName: 'Елена',
    lastName: 'Новикова',
    age: 30,
    experienceYears: 6,
    position: 'Специалист по негабариту',
    resumeLink: 'https://example.com/resume4.pdf',
    status: 'Offered',
    jobId: 'JOB002',
    lastUpdated: '2024-01-18',
  },
  {
    id: '5',
    firstName: 'Дмитрий',
    lastName: 'Волков',
    age: 27,
    experienceYears: 4,
    position: 'Менеджер по продажам',
    resumeLink: 'https://example.com/resume5.pdf',
    status: 'Rejected',
    jobId: 'JOB001',
    lastUpdated: '2024-01-19',
  },
  {
    id: '6',
    firstName: 'Анна',
    lastName: 'Смирнова',
    age: 29,
    experienceYears: 5,
    position: 'Специалист по негабариту',
    resumeLink: 'https://example.com/resume6.pdf',
    status: 'New',
    jobId: 'JOB002',
    lastUpdated: '2024-01-20',
  },
  {
    id: '7',
    firstName: 'Сергей',
    lastName: 'Морозов',
    age: 31,
    experienceYears: 7,
    position: 'Менеджер по продажам',
    resumeLink: 'https://example.com/resume7.pdf',
    status: 'In Progress',
    jobId: 'JOB001',
    lastUpdated: '2024-01-21',
  },
  {
    id: '8',
    firstName: 'Ольга',
    lastName: 'Кузнецова',
    age: 26,
    experienceYears: 2,
    position: 'Специалист по негабариту',
    resumeLink: 'https://example.com/resume8.pdf',
    status: 'Interview',
    jobId: 'JOB002',
    lastUpdated: '2024-01-22',
  },
];

// Mock jobs data
export const mockJobs: Job[] = [
  {
    jobId: 'JOB001',
    jobTitle: 'Менеджер по продажам',
    department: 'Продажи',
    status: 'Open',
  },
  {
    jobId: 'JOB002',
    jobTitle: 'Специалист по негабариту',
    department: 'Логистика',
    status: 'Open',
  },
];
